### ISSUE TITLE
/chapter3/speech_service/README.mdの修正

### ISSUE THREAD

**Issue by kanpapa** [AI-Robot-Book/chapter3#1]
/chapter3/speech_service/README.md に誤記がありました。

こちらはsudoをつける必要があると思われます。
```
apt install portaudio19-dev
apt install pulseaudio
```

音声合成のトピック発行のコマンドですが、

`ros2 topic pub -1 /speech std_msgs/msg/String "{data: 'I will go to the kitchen and grab a bottle.'}`

最後に` " `が必要のようです。

**Comment by yhagiwara** [comment]
ご指摘ありがとうございます。
修正致しました。
